FROM nvidia/cuda:9.0-devel

ADD . /app
WORKDIR /app

RUN apt-get update
RUN apt-get -y install wget

RUN apt-get -y install python2.7 python-pip

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python2.7 get-pip.py

RUN pip2.7 install -r requirements.txt
RUN pip2.7 install cupy-cuda90
CMD /bin/bash
